spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  data:
    # Redis 설정
    redis:
      host: ${REDIS_HOST:host.docker.internal}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  config:
    import:
      - postgres.yml
      - mongo.yml
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
        use_sql_comments: true
        show-sql: true
query:
  path:
    ranking: src/main/resources/query/ranking.sql

schedules:
  cron:
    ranking:
      batch:
        daily: 0 0 0 * * *
        weekly: 0 0 0 * * MON
        monthly: 0 0 0 1 * *
      redis:
        weekly: 0 0 0 * * MON
        monthly: 0 0 0 1 * *
  zone: Asia/Seoul