name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

version-resolver:
  major:
    labels:
      - "🔖 Release"          # 릴리즈 버전
  minor:
    labels:
      - "✨ Feature"          # 기능 추가
  patch:
    labels:
      - "🐛 BugFix"           # 버그 수정
      - "🚑 Hotfix"           # 긴급 수정 (버그성)
      - "♻️ Refactor"         # 리팩터링
      - "✅ Test"             # 테스트 추가/수정
      - "🎨 Style"            # 스타일 수정
      - "💚 Build"            # 빌드 관련
      - "👷 CI"               # CI 설정 수정
      - "📕 Docs"             # 문서/주석 수정
      - "🔗 Chore"            # 기타 설정
      - "🛠️ Merge"            # 충돌 해결
      - "🔀 Branch"            # 브랜치 추가/병합
  default: patch

categories:
  - title: "✨ Features"
    labels:
      - "✨ Feature"

  - title: "🐛 Bug Fixes"
    labels:
      - "🐛 BugFix"
      - "🚑 Hotfix"

  - title: "♻️ Refactors"
    labels:
      - "♻️ Refactor"

  - title: "✅ Tests"
    labels:
      - "✅ Test"

  - title: "🎨 Style Updates"
    labels:
      - "🎨 Style"

  - title: "👷 CI/CD & Build"
    labels:
      - "👷 CI"
      - "💚 Build"

  - title: "📘 Documentation"
    labels:
      - "📕 Docs"

  - title: "🔧 Others"
    labels:
      - "🔗 Chore"
      - "🛠️ Merge"
      - "🔀 Branch"

change-template: "- $TITLE (@$AUTHOR) #$NUMBER"
change-title-escapes: '\<*_&'

template: |
  ## 🚀 What's Changed
  $CHANGES

  ---
  🏷️ Auto-generated by [Release Drafter](https://github.com/release-drafter/release-drafter)
