name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "✨ Feature"
    labels: 
      - "✨ Feature"
  - title: "🚑 Hotfix"
    labels:
      - "🚑 Hotfix"
  - title: "🐛 Bug Fixes"
    labels: 
      - "🐛 BugFix"
exclude-labels:
  - "✅ Test"
 

template: |
  ## 📋 변경점
  $CHANGES
  

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
change-template: "- $TITLE (#$NUMBER)"
