plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
}

group = 'com.midas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

group = 'com.shootpointer'
version = '0.0.1-SNAPSHOT'


allprojects {
    group = 'com.shootpointer'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}


subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }


    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        // PostgreSQL JDBC Driver
        implementation 'org.postgresql:postgresql'

        compileOnly 'org.projectlombok:lombok'
        runtimeOnly 'com.mysql:mysql-connector-j'
        annotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

        //test - log
        testCompileOnly 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
        implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'

        implementation 'org.redisson:redisson-spring-boot-starter:3.18.0'
        testImplementation "org.testcontainers:junit-jupiter:1.20.6"
        testImplementation "org.springframework.boot:spring-boot-testcontainers"

        //MongoDB
        implementation('org.springframework.boot:spring-boot-starter-data-mongodb')
    }
}


tasks.named('test') {
    useJUnitPlatform()
    /**
     * 동시성 제어 테스트 제외 - 제외 이유 : PR시 Jacoco 커버리지 측정 시간 대폭 증가.
     **/
    if (System.getenv("CI") == "true") {
        exclude '**/LikeManagerConcurrencyTest.class'
    }
}
//test
test {
    finalizedBy jacocoTestReport
}

jacoco {
    toolVersion = "0.8.11"
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required.set(true)
    }
    afterEvaluate {
        classDirectories.setFrom(
                files(classDirectories.files.collect {
                    fileTree(dir: it, exclude: [
                            "**/global/config/**",
                            "**/global/exception/**",
                            "**/global/dto/**",
                            "**/global/aop/**",
                            "**/global/entity/**",
                            "**/global/common/**",
                            "**/HealthCheckController.class",
                            "ShootPointerApplication.class",
                            "**/domain/**/entity/**",
                            "**/global/annotation/**",
                            "**/test/**",
                            "**/batch/listener/**",
                            "**/batch/config/**",
                            "**/batch/validator/**"
                    ])
                })
        )
    }
}