version: "3.9"

services:
  # PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shootpointer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # MongoDB
  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - spring-network
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    # Spring Boot Application
    # ==========================================
    # [App 1] API Server (웹 요청 처리)
    # ==========================================
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: api-server
    container_name: shootpointer-api
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - spring-network
    restart: always
    environment:
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATA_REDIS_PORT=6379

  # ==========================================
  # [App 2] Batch Server (배치)
  # ==========================================
  batch-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: batch-server
    container_name: shootpointer-batch
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - spring-network

  # Elasticsearch
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elesticsearch
    container_name: elasticsearch
    user: "0"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      logger.level: "debug"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    entrypoint: >
      bash -c "
        mkdir -p /usr/share/elasticsearch/logs &&
        chmod -R 775 /usr/share/elasticsearch/logs &&
        chown -R 1000:1000 /usr/share/elasticsearch &&
        echo 'Starting Elasticsearch...' &&
        su -s /bin/bash elasticsearch -c '/usr/local/bin/docker-entrypoint.sh eswrapper'
      "
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - spring-network
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - spring-network
    restart: always

networks:
  spring-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
  mongo-config:
  esdata:

