# Settings
spring:
  application:
    name: shootpointer
  profiles:
    active: dev


# -------------------------
# [OpenCV Settings]
# -------------------------
opencv:
  url: http://localhost:8888
  api:
    post:
      send-img: back-number
    get:
      fetch-video: highlight
  proxy:
    upload-video: upload
