#Test 환경
spring:
  # 데이터소스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shootpointer}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}

  elasticsearch:
    mode: ${SPRING_ELASTICSEARCH_MODE:local}
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    connection-timeout: 10s
    socket-timeout: 30s
    restclient:
      sniffer:
        interval: 5m
  data:
    # Redis 설정
    redis:
      custom:
        ranking:
          key:
            weekly: ranking:WEEKLY
            monthly: ranking:MONTHLY

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

video:
  path: ${java.io.tmpdir}/videos
